### ISSUE TITLE
Select component doesn't work properly

### ISSUE THREAD

**Issue by abaklanov** [antonreshetov/vue-form-components#12]
Hey 

I'm trying to utilize Select component, but had no luck so far.
An element shows up, but no dropdown is displayed after clicking it.

I have a jsfiddle example:
https://jsfiddle.net/b265fqz9/2/

Could you give me a hint on what could be a problem with my code?

Thanks.

**Comment by antonreshetov** [comment]
Hi @abaklanov all right, the only thing is missing props `v-model` in `vue-select`. But still pop-up does not open. I think is problem in iframe, in which jsfiddle paste html part.

**Comment by abaklanov** [comment]
Thanks for the reply on such short notice

But it was just an example. It behaves the exact same way inside of my project.
I noticed that popper.js doesn't show up in the markup. Is there any known issues with it in regards of using your tool?

Thanks

**Comment by antonreshetov** [comment]
I tested in new vue project and install vfc from npm. And I had no problems. This is weird

**Comment by abaklanov** [comment]
Ok. I'll try to find what's wrong.
